import apiFetch from '@wordpress/api-fetch';

const OFFLINE_CACHE_KEY = 'es_scrum_offline_cache';
const OFFLINE_QUEUE_KEY = 'es_scrum_offline_queue';

// Helper to get from local storage safely
const getFromStorage = (key, defaultValue) => {
    try {
        const stored = localStorage.getItem(key);
        return stored ? JSON.parse(stored) : defaultValue;
    } catch (e) {
        console.error('Error reading from localStorage', e);
        return defaultValue;
    }
};

// Helper to save to local storage safely
const saveToStorage = (key, value) => {
    try {
        localStorage.setItem(key, JSON.stringify(value));
    } catch (e) {
        console.error('Error writing to localStorage', e);
    }
};

// Generate a temporary ID that won't collide with numeric database IDs
const generateTempId = () => `temp_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// Get the current cache
export const getCache = () => getFromStorage(OFFLINE_CACHE_KEY, {});

// Get the current offline queue
export const getQueue = () => getFromStorage(OFFLINE_QUEUE_KEY, []);

// Check if we are currently online
export const isOnline = () => navigator.onLine;

let isSyncing = false;

// Process the offline queue when coming back online
export const syncOfflineQueue = async () => {
    if (!isOnline() || isSyncing) return;

    const queue = getQueue();
    if (queue.length === 0) return;

    isSyncing = true;
    console.log(`Starting sync of ${queue.length} offline actions...`);
    window.dispatchEvent(new Event('es_scrum_sync_start'));

    // We'll keep a map of temp IDs to real IDs generated by the server
    const idMap = new Map();
    const remainingQueue = [];

    // Process sequentially
    for (const action of queue) {
        let { path, method, data, tempId, type } = action;

        // If data contains references to temporary IDs, update them with real IDs
        if (data) {
            // Check if this action relates to a parent (e.g., adding a comment to a task that was created offline)
            if (data.task_id && idMap.has(data.task_id)) {
                data.task_id = idMap.get(data.task_id);
            }
            if (data.parent_id && idMap.has(data.parent_id)) {
                data.parent_id = idMap.get(data.parent_id);
            }
        }

        // If the path contains a temp ID (e.g., /es-scrum/v1/tasks/temp_123), update the path
        if (path) {
            for (const [temp, real] of idMap.entries()) {
                if (path.includes(temp)) {
                    path = path.replace(temp, real);
                }
            }
        }

        try {
            console.log(`Syncing action: ${method} ${path}`, data);
            const response = await apiFetch({ path, method, data });

            // If this was a creation (POST), map the temp ID to the real ID
            if (method === 'POST' && tempId && response && response.id) {
                idMap.set(tempId, response.id);
            }
        } catch (error) {
            console.error(`Failed to sync action: ${method} ${path}`, error);
            // Decide how to handle failures. For now, we drop it to prevent infinite blockers,
            // but in a production app, we might want to keep it or alert the user.
        }
    }

    // Clear the queue once processed
    saveToStorage(OFFLINE_QUEUE_KEY, []);
    isSyncing = false;
    console.log('Sync complete.');

    // Broadcast an event so components can refresh their data
    window.dispatchEvent(new Event('es_scrum_sync_complete'));
};

// Listen for network changes to trigger sync
if (typeof window !== 'undefined') {
    window.addEventListener('online', syncOfflineQueue);
}

// The main wrapper
const offlineSyncFetch = async (options) => {
    const { path, method = 'GET', data, parse = true } = options;

    // We only intercept requests directed at our specific endpoints or some common wp endpoints
    const isOurApi = path.includes('/es-scrum/v1/') || path.includes('/wp/v2/users/me');

    if (!isOurApi) {
        return apiFetch(options);
    }

    if (isOnline()) {
        try {
            // Attempt normal fetch
            const response = await apiFetch(options);

            // If GET, update cache
            if (method === 'GET' && parse !== false) {
                const cache = getCache();
                cache[path] = response;
                saveToStorage(OFFLINE_CACHE_KEY, cache);
            }

            return response;
        } catch (error) {
            // If it fails due to network error while ostensibly "online", 
            // fallback to offline logic if possible
            if (error.message && error.message.includes('fetch')) {
                return handleOffline(options);
            }
            throw error;
        }
    } else {
        return handleOffline(options);
    }
};

const handleOffline = async (options) => {
    const { path, method = 'GET', data, parse = true } = options;

    if (method === 'GET') {
        const cache = getCache();
        if (cache[path] !== undefined) {
            console.log(`[Offline mode] Serving cached data for ${path}`);
            // If parse is false, simulate a Response object.  Our components that use parse: false
            // (like UserProfileModal) expect res.json() and headers. 
            if (parse === false) {
                return {
                    json: async () => cache[path],
                    headers: new Headers({ 'X-WP-TotalPages': '1', 'X-WP-Total': cache[path].length?.toString() || '1' })
                };
            }
            return cache[path];
        } else {
            throw new Error(`Offline and no cached data available for ${path}`);
        }
    } else {
        // Queue the mutation
        const queue = getQueue();
        const tempId = generateTempId();

        const action = {
            path,
            method,
            data,
            tempId,
            timestamp: Date.now()
        };

        queue.push(action);
        saveToStorage(OFFLINE_QUEUE_KEY, queue);

        console.log(`[Offline mode] Queued action: ${method} ${path}`);

        // Return a mock response for optimistic updates
        if (method === 'POST') {
            // Try to construct a reasonable mock object
            const mockResponse = { id: tempId, ...data, created_at: new Date().toISOString() };
            return mockResponse;
        } else if (method === 'PATCH' || method === 'DELETE') {
            return { message: 'Action queued offline', id: 'queued' };
        }

        return { success: true, offline: true };
    }
};

// Export the wrapper as default (so it mimics apiFetch)
export default offlineSyncFetch;
